### ISSUE TITLE
type vs data-vis-type

### ISSUE THREAD

**Issue by glynnbird** [ibm-cds-labs/simple-data-vis#2]
The [wiki](https://github.com/ibm-cds-labs/simple-data-vis/wiki/API#attrname-value) says "data-vis-type" but the [sample code](https://github.com/ibm-cds-labs/simple-data-vis/wiki/API#ontype-callback) says "type".

I'm pretty sure it should be "data-vis-type" ?

**Comment by vabarbosa** [comment]
wiki and readme have been updated with additional info and more examples
